### ISSUE TITLE
wtf no lightmode pls 

### ISSUE THREAD

**Issue by ollecoffee** [p1xelHer0/p1xelher0-atom-syntax#1]
## hello team ##

i would like light mode pls 
how else can i use this on vacation in sunny beach??

br
olle

**Comment by p1xelHer0** [comment]
I've created a light version of this theme, just for you @ollegz !
Please see [p1xelher0-light-syntax](https://github.com/p1xelHer0/p1xelher0-light-atom-syntax/)

Enjoy!
