### ISSUE TITLE
How to install the theme?

### ISSUE THREAD

**Issue by liuchangxing** [p1xelHer0/p1xelher0-atom-syntax#2]
![qq 20161101141453](https://cloud.githubusercontent.com/assets/22342099/19881070/9fb89b5a-a03d-11e6-9948-3efc8a6dab1f.png)
It has no effect.

**Comment by liuchangxing** [comment]
Can you tell me how to install it?

**Comment by p1xelHer0** [comment]
It looks like you are still using the "Atom Dark" syntax theme.

After you have installed this theme, go to "Settings" (by pressing Ctrl + , on Windows by default). When in the settings menu, select "Themes" and set the Syntax Theme to "P1xelher0" in the dropdown.

I just verified the PHP file-extension myself and it looks like this as of now:
<img width="653" alt="example-php-1" src="https://cloud.githubusercontent.com/assets/6594842/19883682/f3b0cf02-a015-11e6-9298-aace8847df87.png">

**Comment by liuchangxing** [comment]
no no.Maybe if you teach me to install the theme, it will be effective.
![qq 20161101175954](https://cloud.githubusercontent.com/assets/22342099/19886198/2f1fcea2-a05d-11e6-8394-d67943f9c246.png)

**Comment by liuchangxing** [comment]
My "community theme" is all like this.
They all have no effect.

**Comment by liuchangxing** [comment]
I like your theme.
![image](https://cloud.githubusercontent.com/assets/22342099/19886619/095f966e-a05f-11e6-9bbb-d31cb2a2770a.png)
-

**Comment by p1xelHer0** [comment]
How do you usually install themes? I suggest you remove the theme from Atom and try reinstalling it. Quit Atom and run the following command in your terminal:

`apm install p1xelher0-syntax`

<img width="579" alt="exmaple-apm-install-1" src="https://cloud.githubusercontent.com/assets/6594842/19887271/c8484b94-a027-11e6-993d-36bd0c32bdb9.png">

When that is done you should be able to start Atom and select the theme.

You can also install it with the GUI, by going to "Settings" > "Install" > Select "Themes" and search for "pixelher0-syntax" and installing it there.

Else I'd have to refer to the official documentation for Atom: http://flight-manual.atom.io/using-atom/sections/atom-packages/

**Comment by liuchangxing** [comment]
![qq 20161101190050](https://cloud.githubusercontent.com/assets/22342099/19887793/a09323a6-a065-11e6-878a-e6791e5f0927.png)

I usually do this.

**Comment by p1xelHer0** [comment]
Try installing it with the methods I used above instead of using `npm` and see if anything changes. I've never installed a package directly using `npm` myself. I only use `apm` - the [Atom Package Manager](https://github.com/atom/apm)

**Comment by liuchangxing** [comment]
'apm'is not an internal or external command, nor a program that can be run
Batch file or batch file.

**Comment by liuchangxing** [comment]
Can not install " Atom Package Manager".
![qq 20161101191928](https://cloud.githubusercontent.com/assets/22342099/19888215/38ee9b4c-a068-11e6-9776-9461e10ba65f.png)

**Comment by p1xelHer0** [comment]
Since the case seems to be that you can't install any Community Theme whatsoever, this seems to be more related to your Atom installation than this repository. Try to install the Syntax Theme with the GUI instead of using the CLI. 

Like stated in the previous comment:

> You can also install it with the GUI, by going to "Settings" > "Install" > Select "Themes" and search for "pixelher0-syntax" and installing it there.

Else, try installing a clean version of Atom and installing it with the GUI again.

If that doesn't work I'd have to refer to the [Atom documentation for installing packages](http://flight-manual.atom.io/using-atom/sections/atom-packages/) or the [Atom editor repository](https://github.com/atom/atom) to see if someone there can help you installing community themes.
